INFO:     Will watch for changes in these directories: ['/mnt/c/Users/pc/Desktop/HNG_PROJECTS/messaging_sys_python_nginx/messaging-sys-with-rabbitmq-celery-python-nginx/messaging_sys_project']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [652] using WatchFiles
INFO:     Started server process [654]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:60754 - "GET /send-email/?sendmail=uyioboite@gmail.com HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44398 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:60760 - "GET /send-email/?sendmail=uyioboite@gmail.com HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44414 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:47878 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:47880 - "GET /send-email/?sendmail=uyioboite@gmail.com HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:49638 - "GET /send-email/?sendmail=uyioboite@gmail.com HTTP/1.1" 500 Internal Server Error
INFO:     Will watch for changes in these directories: ['/mnt/c/Users/pc/Desktop/HNG_PROJECTS/messaging_sys_python_nginx/messaging-sys-with-rabbitmq-celery-python-nginx/messaging_sys_project']
ERROR:    [Errno 98] Address already in use
INFO:     Will watch for changes in these directories: ['/mnt/c/Users/pc/Desktop/HNG_PROJECTS/messaging_sys_python_nginx/messaging-sys-with-rabbitmq-celery-python-nginx/messaging_sys_project']
ERROR:    [Errno 98] Address already in use
INFO:     127.0.0.1:45166 - "GET /send-email/?sendmail=uyioboite@gmail.com HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:45166 - "GET /send-email/?sendmail=uyioboite@gmail.com HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:50582 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:50582 - "GET / HTTP/1.1" 200 OK
INFO:     Will watch for changes in these directories: ['/mnt/c/Users/pc/Desktop/HNG_PROJECTS/messaging_sys_python_nginx/messaging-sys-with-rabbitmq-celery-python-nginx/messaging_sys_project']
ERROR:    [Errno 98] Address already in use
INFO:     127.0.0.1:53794 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:37760 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:35780 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:35778 - "GET / HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [654]
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 410, in main
    run(
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 572, in run
    ChangeReload(config, target=server.run, sockets=[sock]).run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/supervisors/basereload.py", line 52, in run
    for changes in self:
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/supervisors/basereload.py", line 71, in __next__
    return self.should_restart()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/supervisors/watchfilesreload.py", line 84, in should_restart
    changes = next(self.watcher)
  File "/usr/local/lib/python3.8/dist-packages/watchfiles/main.py", line 121, in watch
    raw_changes = watcher.watch(debounce, step, rust_timeout, stop_event)
_rust_notify.WatchfilesRustInternalError: error in underlying watcher: IO error for operation on /mnt/c/Users/pc/Desktop/HNG_PROJECTS/messaging_sys_python_nginx/messaging-sys-with-rabbitmq-celery-python-nginx/messaging_sys_project/myenv/lib/python3.8/site-packages/pika-1.3.2-py3.8.egg/pika/__pycache__/exceptions.cpython-38.pyc.140707498190864: No such file or directory (os error 2) about ["/mnt/c/Users/pc/Desktop/HNG_PROJECTS/messaging_sys_python_nginx/messaging-sys-with-rabbitmq-celery-python-nginx/messaging_sys_project/myenv/lib/python3.8/site-packages/pika-1.3.2-py3.8.egg/pika/__pycache__/exceptions.cpython-38.pyc.140707498190864"]
